version: '3'
services:
  flask:
    build: ./
    container_name: backend-flask
    environment:
      - PYTHONUNBUFFERED=True                   
    restart: on-failure
    volumes:
      - ./:/backend
    ports:
      - "5000:5000"
    command: gunicorn app:app -b 0.0.0.0:5000 --reload
  